version: "3.9"

services:
  webapi:
    build: ./webapi
    ports: 
      - "81:80"
    environment:
      - ConnectionString_ConnectionDB="Server=mssql;Initial Catalog=WebApiDB;Persist Security Info=False;User ID=sa;Password=FullStack2023*;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
    depends_on:
      - mssql
  mssql:
    build: ./data
    ports:
      - "1434:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: