// <auto-generated />
using FullStackDev.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStackDev.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20230118073240_DBMigration2")]
    partial class DBMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "a1e84b44-6944-4f27-af9b-15e3c935faee",
                            Active = true,
                            Name = "Don Quixote",
                            Price = 12f,
                            TypeId = "b00db9eb-7650-4878-b814-8a96d5a8220e"
                        },
                        new
                        {
                            Id = "2210eb18-7a6a-4845-bd1d-6f137450a06e",
                            Active = true,
                            Name = "Microwave",
                            Price = 30f,
                            TypeId = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e"
                        },
                        new
                        {
                            Id = "44604cfa-6597-470c-a838-ecb7cf1f1e62",
                            Active = true,
                            Name = "Pizza",
                            Price = 15f,
                            TypeId = "070e30e7-488b-47e3-ad28-4379b9be6185"
                        },
                        new
                        {
                            Id = "895d5bdc-6a3c-4a23-8d03-67085184d35c",
                            Active = true,
                            Name = "Chair",
                            Price = 25f,
                            TypeId = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f"
                        },
                        new
                        {
                            Id = "ea1520ad-4d65-42ad-831f-13450c149787",
                            Active = true,
                            Name = "Lego",
                            Price = 30f,
                            TypeId = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.ProductType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = "b00db9eb-7650-4878-b814-8a96d5a8220e",
                            Name = "Books"
                        },
                        new
                        {
                            Id = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = "070e30e7-488b-47e3-ad28-4379b9be6185",
                            Name = "Food"
                        },
                        new
                        {
                            Id = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.HasOne("FullStackDev.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
