// <auto-generated />
using FullStackDev.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStackDev.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20230118071814_DBMigration")]
    partial class DBMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "0d039ad9-4c3d-49ca-9966-7b893e8d0944",
                            Active = true,
                            Name = "Books",
                            Price = 10f,
                            TypeId = "b00db9eb-7650-4878-b814-8a96d5a8220e"
                        },
                        new
                        {
                            Id = "28ce8f23-6943-4f5f-af3b-73de3143751e",
                            Active = true,
                            Name = "Electronics",
                            Price = 10f,
                            TypeId = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e"
                        },
                        new
                        {
                            Id = "adae976f-8781-4f91-91a8-12cb2ca412cf",
                            Active = true,
                            Name = "Food",
                            Price = 10f,
                            TypeId = "070e30e7-488b-47e3-ad28-4379b9be6185"
                        },
                        new
                        {
                            Id = "43b11ab4-16ac-47d3-8ede-5b9f49ae04e3",
                            Active = true,
                            Name = "Furniture",
                            Price = 10f,
                            TypeId = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f"
                        },
                        new
                        {
                            Id = "cad4b686-4b76-4818-8f80-ef2fb8c0a811",
                            Active = true,
                            Name = "Toys",
                            Price = 10f,
                            TypeId = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.ProductType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = "b00db9eb-7650-4878-b814-8a96d5a8220e",
                            Name = "Books"
                        },
                        new
                        {
                            Id = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = "070e30e7-488b-47e3-ad28-4379b9be6185",
                            Name = "Food"
                        },
                        new
                        {
                            Id = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.HasOne("FullStackDev.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
