// <auto-generated />
using FullStackDev.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStackDev.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20230119062634_DBMigration1")]
    partial class DBMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "f6095b43-57f1-49a7-9acf-ac3d145fef4f",
                            IsActive = true,
                            Name = "Don Quixote",
                            Price = 12f,
                            ProductTypeId = "b00db9eb-7650-4878-b814-8a96d5a8220e"
                        },
                        new
                        {
                            Id = "cf994cb1-dc3c-4822-93f7-a7422a016ca9",
                            IsActive = true,
                            Name = "Microwave",
                            Price = 30f,
                            ProductTypeId = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e"
                        },
                        new
                        {
                            Id = "50909b94-5134-4392-be80-13bcccd2086c",
                            IsActive = true,
                            Name = "Pizza",
                            Price = 15f,
                            ProductTypeId = "070e30e7-488b-47e3-ad28-4379b9be6185"
                        },
                        new
                        {
                            Id = "7caba613-eaa2-4c83-9d47-97b438169f95",
                            IsActive = true,
                            Name = "Chair",
                            Price = 25f,
                            ProductTypeId = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f"
                        },
                        new
                        {
                            Id = "7a852c93-ca4f-4ab5-84ac-c8b70927506e",
                            IsActive = true,
                            Name = "Lego",
                            Price = 30f,
                            ProductTypeId = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.ProductType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = "b00db9eb-7650-4878-b814-8a96d5a8220e",
                            Name = "Books"
                        },
                        new
                        {
                            Id = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = "070e30e7-488b-47e3-ad28-4379b9be6185",
                            Name = "Food"
                        },
                        new
                        {
                            Id = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.HasOne("FullStackDev.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
