// <auto-generated />
using FullStackDev.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStackDev.Migrations
{
    [DbContext(typeof(WebApiContext))]
    partial class WebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "7087d279-0d0d-40f2-8521-7594cd4085f0",
                            Active = true,
                            Name = "Don Quixote",
                            Price = 12f,
                            ProductTypeId = "b00db9eb-7650-4878-b814-8a96d5a8220e"
                        },
                        new
                        {
                            Id = "bb904871-2627-404d-809d-aec7e60bbe40",
                            Active = true,
                            Name = "Microwave",
                            Price = 30f,
                            ProductTypeId = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e"
                        },
                        new
                        {
                            Id = "5cbaed4e-4a9e-495e-9dd1-310d931156c3",
                            Active = true,
                            Name = "Pizza",
                            Price = 15f,
                            ProductTypeId = "070e30e7-488b-47e3-ad28-4379b9be6185"
                        },
                        new
                        {
                            Id = "83cdb933-1daa-40d2-be0f-bde9810510b1",
                            Active = true,
                            Name = "Chair",
                            Price = 25f,
                            ProductTypeId = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f"
                        },
                        new
                        {
                            Id = "75a248e1-91a0-4698-bf57-616567cf6e08",
                            Active = true,
                            Name = "Lego",
                            Price = 30f,
                            ProductTypeId = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.ProductType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = "b00db9eb-7650-4878-b814-8a96d5a8220e",
                            Name = "Books"
                        },
                        new
                        {
                            Id = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = "070e30e7-488b-47e3-ad28-4379b9be6185",
                            Name = "Food"
                        },
                        new
                        {
                            Id = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("FullStackDev.Models.Product", b =>
                {
                    b.HasOne("FullStackDev.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
